os: linux
distro: bionic

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter config --enable-web
  - sudo apt-get -qq update
  - sudo apt-get install gcc libpq-dev -y
  - sudo apt-get install python-dev  python-pip -y
  - sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
  - sudo apt-get -y install python3-pip
  - sudo apt-get install python3-setuptools
  - pip3 install wheel

script:
  - ls -la
  - cd front
  - ls -la
  - flutter clean
  - flutter build web --release
  - cd ..
  - cd back
  - pip3 install -r requirements.txt
  - cd ..

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: front/build/web
    on:
      branch: master
  - provider: heroku
    app: tcc-opus-back
    api_key: $HEROKU_TOKEN
    on:
      branch: master