os: linux
distro: bionic

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter config --enable-web

script:
  - ls -la
  - cd front
  - ls -la
  - flutter build web

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: front/build/web
# language: python

# deploy:
# - provider: s3
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   local_dir: dpl_cd_upload
#   skip_cleanup: true
#   on: &2
#     repo: rodipm/TccOpus
#   bucket: tccopusbucket
#   region: us-east-2
# - provider: codedeploy
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   bucket: tccopusbucket
#   key: latest.zip
#   bundle_type: zip
#   application: TccOpus
#   deployment_group: TccOpusImplantacao
#   region: us-east-2
#   on: *2
# script:
#   - cd front/build/web
#   - zip -r latest *
#   - mkdir -p dpl_cd_upload
#   - mv latest.zip dpl_cd_upload/latest.zip
#   - echo ok
# matrix:
#   include:
#     - language: rust
#       rust:
#         - stable
#       jobs:
#         allow_failures:
#           - rust: nightly
#         fast_finish: true
#     - language: node.js
#       node_js: "12.0"
#       before_script:
#         - cd angular-application
#       script:
#         - npm install
#         - ng build --prod